apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-084d2b8a74103917b

---

apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: ebs-static
spec:
  storageClassName: ""
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi